name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos_x86_64:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Crystal
        run: brew install crystal
      - name: Build the binary
        # Statically link most non-system libraries
        run: |
          cc=$(env CRYSTAL_LIBRARY_PATH=`pwd`/libs/x86_64-apple-darwin shards build --target="x86_64-apple-darwin" --cross-compile --release -Dpreview_mt | tail -n 1)
          eval $cc
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: zap_x86_64-apple-darwin
          path: ./bin/zap
  macos_arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Crystal
        run: brew install crystal
      - name: Build the binary
        # Statically link most non-system libraries
        run: |
          cc=$(env CRYSTAL_LIBRARY_PATH=`pwd`/libs/arm64-apple-darwin shards build --target="arm64-apple-darwin" --cross-compile --release | tail -n 1 | sed -e "s/-rdynamic/--target=arm64-apple-darwin -rdynamic/g")
          eval $cc
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: zap_arm64-apple-darwin
          path: ./bin/zap
  linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build the static binary
        run: shards build --production --release -Dpreview_mt --static --no-debug --stats
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: zap_x86_64-linux-musl
          path: ./bin/zap
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Build the binary
        shell: bash
        run: |
          shards build --progress --release --no-debug --stats
          ls -al ./bin
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: zap_x86_64-pc-win32.exe
          path: ${{ github.workspace }}\bin\zap.exe
