name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  specs:
    name: Specs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install dependencies
        run: crystal projects.cr install
      - name: Run tests
        run: crystal projects.cr spec
      - name: Run tests (multithreaded)
        run: crystal projects.cr spec -Dpreview_mt
  launch:
    name: Build and check if the binary is working
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install dependencies
        run: crystal projects.cr install
      - name: Build
        run: crystal projects.cr build:cli
      - name: Print version
        run: ./packages/cli/bin/zap --version
